version: "3.3"
services:
  db-partner:
    container_name: db-partner
    image: mongo:3.4-jessie
    ports:
      - "27017:27017"
    volumes:
      - database-volume:/data/db

  inspect-partner:
    container_name: inspect-partner
    image: mongoclient/mongoclient
    restart: on-failure
    depends_on:
      - db-partner
    environment:
      MONGO_URL: "mongodb://db-partner:27017/project-partner"
    volumes:
      - nosqlclient-volume:/data/db
    ports:
      - "9000:3000"

  api-partner:
    container_name: api-partner
    image: api-partner
    restart: on-failure
    build:
      context: .
    ports:
      - "5000:80"
    depends_on:
      - db-partner
    volumes:
      - ./app.py:/api/app.py
    environment:
      PORT: "80"
      FIELD_ADDRESS: "address"
      FIELD_COVERAGE_AREA: "coverageArea"
      FIELD_DOCUMENT: "document"
      FIELD_OWNER_NAME: "ownerName"
      FIELD_TRADING_NAME: "tradingName"
      ERROR_TEXT_GEO: "Can`t extract geo keys"
      ERROR_TEXT_NOT_FOUND: "Not found"
      ERROR_TEXT_REQUIRED: "Required field"
      ERROR_TEXT_STRING: "Type requered string"
      ERROR_TEXT_DOCUMENT: "Document invalid"
      ERROR_TEXT_MIN_LENGTH: "Min length"
      ERROR_TEXT_LENGTH: "Length"
      DBAAS_MONGODB_DATABASE: "project-partner"
      DBAAS_MONGODB_ENDPOINT: "mongodb://db-partner:27017/project-partner"
    #tty: true
    command: honcho start

volumes:
  database-volume:
  nosqlclient-volume:
