version: "3.3"
services:
  db-api-partner:
    container_name: db-api-partner
    image: mongo:3.4-jessie
    ports:
      - "27017:27017"
    volumes:
      - database-volume:/data/db
    networks:
      - db_net

  api-partner:
    container_name: api-partner
    image: api-partner
    restart: on-failure
    build:
      context: .
    ports:
      - "5000:80"
    links:
      - db-api-partner
    depends_on:
      - db-api-partner
    volumes:
      - ./app.py:/api/app.py
      - ./logger_config.py:/api/logger_config.py
      - ./controller:/api/controller
      - ./business:/api/business
      - ./model:/api/model
      - ./routes:/api/routes
      - ./tests:/api/tests
    environment:
      PORT: "80"
      FIELD_ID: "id"
      FIELD_ADDRESS: "address"
      FIELD_COVERAGE_AREA: "coverageArea"
      FIELD_DOCUMENT: "document"
      FIELD_OWNER_NAME: "ownerName"
      FIELD_TRADING_NAME: "tradingName"
      ERROR_TEXT_GEO: "Cant extract geo keys"
      ERROR_TEXT_NOT_FOUND: "Not found"
      ERROR_TEXT_REQUIRED: "Required field"
      ERROR_TEXT_STRING: "Type requered string"
      ERROR_TEXT_NUMBER: "Type requered number"
      ERROR_TEXT_OBJECT: "Type requered object valid"
      ERROR_TEXT_LIST: "Type requered list valid"
      ERROR_TEXT_DOCUMENT: "Document invalid"
      ERROR_TEXT_MIN_LENGTH: "Min length"
      ERROR_TEXT_LENGTH: "Length"
      ERROR_TEXT_INCORRECT: "incorrect"
      DBAAS_MONGODB_DATABASE: "db-api-partner"
      DBAAS_MONGODB_ENDPOINT: "mongodb://userSystem:teste123@db-api-partner:27017/db-api-partner"
      GUNICORN_MAX_REQUESTS: "10000"
      GUNICORN_WORKERS: "3"
      HOST: "0.0.0.0"
      LOG_LEVEL: "DEBUG"
    command: honcho start
    networks:
      - db_net

networks:
  db_net:

volumes:
  database-volume:
